name: CI Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          cache: 'maven'
          distribution: 'temurin'

      - name: build with maven
        run: |
          export MAVEN_OPTS="--add-exports=java.xml/com.sun.org.apache.xerces.internal.parsers=ALL-UNNAMED --add-exports=java.xml/com.sun.org.apache.xerces.internal.util=ALL-UNNAMED" # needed for JDK 16+ only
          mvn -B install

  older-wildfly:
# comment-out the following line when this FP branch supports only one WF version and thus testing with older WF builds isn't needed
#    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wildfly: [36.0.1.Final, 37.0.1.Final]
    name: build with wildfly ${{matrix.wildfly}}

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          cache: 'maven'
          distribution: 'temurin'

      - name: build
        run: mvn -B install

      - name: test with an older wildfly version
        run: mvn -B test -Dversion.org.wildfly=${{matrix.wildfly}} -pl testsuite/integration,testsuite/server-tck,quickstart
