name: CI Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 14, 17]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v1.4.3
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: build with maven
        run: |
          export MAVEN_OPTS="--add-exports=java.xml/com.sun.org.apache.xerces.internal.parsers=ALL-UNNAMED --add-exports=java.xml/com.sun.org.apache.xerces.internal.util=ALL-UNNAMED" # needed for JDK 16+ only
          mvn -B install

  older-wildfly:
# uncomment the following line when this FP branch supports only one WF version and thus testing with older WF builds isn't needed
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wildfly: [28.0.1.Final, 29.0.1.Final]
    name: build with wildfly ${{matrix.wildfly}}

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-wf-${{ matrix.wildfly }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v1.4.3
        name: set up jdk 11
        with:
          java-version: 11

      - name: build
        run: mvn -B install

      - name: test with an older wildfly version
        run: mvn -B test -Dversion.org.wildfly=${{matrix.wildfly}} -pl testsuite/integration,testsuite/server-tck,quickstart
